# Generated by Django 5.1.4 on 2025-01-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin',
        ),
    ]
